version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dotnet-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s7lq825ncn5b"
s3_prefix = "dotnet-sam"
region = "us-east-1"
profile = "sandbox"
capabilities = "CAPABILITY_IAM"

